# Generated by Django 5.2.9 on 2026-01-12 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course_Program_Batch', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('name',)},
        ),
        migrations.RemoveField(
            model_name='batch',
            name='program',
        ),
    ]
