# Generated by Django 5.2.9 on 2026-01-12 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_Program_Batch', '0002_alter_batch_unique_together_remove_batch_program'),
        ('accounts', '0006_role_is_admin'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='batch',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='accounts.client'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('name', 'client')},
        ),
    ]
