# Generated by Django 5.2.9 on 2025-12-30 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Unique permission code (e.g., 'user.create')", max_length=100, unique=True)),
                ('name', models.CharField(help_text='Display name for the permission', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('USER', 'User Management'), ('ROLE', 'Role Management'), ('CONTENT', 'Content Management'), ('STUDENT', 'Student Operations'), ('TEACHER', 'Teacher Operations'), ('SYSTEM', 'System Operations'), ('REPORT', 'Reports & Analytics'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'permissions',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.AddField(
            model_name='role',
            name='is_student_specific',
            field=models.BooleanField(default=False, help_text='Role specific to students'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_superadmin',
            field=models.BooleanField(default=False, help_text='Super admin role with all permissions'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_teacher_specific',
            field=models.BooleanField(default=False, help_text='Role specific to teachers'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_permissions', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='accounts.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.role')),
            ],
            options={
                'db_table': 'role_permissions',
                'ordering': ['-assigned_at'],
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
