# Generated by Django 5.2.9 on 2026-01-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_client_clientdeleted_clientsettings_userdeleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='student_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of students for this client'),
        ),
        migrations.AddField(
            model_name='client',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='subscription_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='teacher_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of teachers for this client'),
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='is_subscription_base_client',
            field=models.BooleanField(default=False, help_text='Indicates if client is subscription based'),
        ),
    ]
