# Generated by Django 5.2.9 on 2026-01-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_client_student_count_client_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
