# Generated by Django 5.2.9 on 2026-01-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_client_is_delete_clientsettings_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='admin role with all permissions'),
        ),
    ]
